/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as TeacherSettingsRouteImport } from './routes/teacher.settings'
import { Route as TeacherProfileRouteImport } from './routes/teacher.profile'
import { Route as TeacherModulesRouteImport } from './routes/teacher.modules'
import { Route as TeacherLeaderboardRouteImport } from './routes/teacher.leaderboard'
import { Route as TeacherDashboardRouteImport } from './routes/teacher.dashboard'
import { Route as TeacherClassesRouteImport } from './routes/teacher.classes'
import { Route as TeacherAnalyticsRouteImport } from './routes/teacher.analytics'
import { Route as StudentProgressRouteImport } from './routes/student.progress'
import { Route as StudentJoinClassRouteImport } from './routes/student.join-class'
import { Route as StudentGradesRouteImport } from './routes/student.grades'
import { Route as TeacherQuestsCreateRouteImport } from './routes/teacher.quests.create'
import { Route as TeacherClassesClassIdRouteImport } from './routes/teacher.classes_.$classId'
import { Route as StudentProfileEditRouteImport } from './routes/student.profile.edit'
import { Route as StudentClassesClassIdRouteImport } from './routes/student.classes.$classId'
import { Route as StudentQuestsQuestIdLessonRouteImport } from './routes/student.quests.$questId.lesson'
import { Route as StudentQuestsQuestIdGameRouteImport } from './routes/student.quests.$questId.game'
import { Route as StudentModulesModuleIdQuizRouteImport } from './routes/student.modules.$moduleId.quiz'
import { Route as StudentModulesModuleIdLessonRouteImport } from './routes/student.modules.$moduleId.lesson'
import { Route as StudentModulesModuleIdGameRouteImport } from './routes/student.modules.$moduleId.game'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherSettingsRoute = TeacherSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherModulesRoute = TeacherModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherLeaderboardRoute = TeacherLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassesRoute = TeacherClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAnalyticsRoute = TeacherAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRoute,
} as any)
const StudentJoinClassRoute = StudentJoinClassRouteImport.update({
  id: '/join-class',
  path: '/join-class',
  getParentRoute: () => StudentRoute,
} as any)
const StudentGradesRoute = StudentGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherQuestsCreateRoute = TeacherQuestsCreateRouteImport.update({
  id: '/quests/create',
  path: '/quests/create',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassesClassIdRoute = TeacherClassesClassIdRouteImport.update({
  id: '/classes_/$classId',
  path: '/classes/$classId',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentProfileEditRoute = StudentProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => StudentRoute,
} as any)
const StudentClassesClassIdRoute = StudentClassesClassIdRouteImport.update({
  id: '/classes/$classId',
  path: '/classes/$classId',
  getParentRoute: () => StudentRoute,
} as any)
const StudentQuestsQuestIdLessonRoute =
  StudentQuestsQuestIdLessonRouteImport.update({
    id: '/quests/$questId/lesson',
    path: '/quests/$questId/lesson',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentQuestsQuestIdGameRoute =
  StudentQuestsQuestIdGameRouteImport.update({
    id: '/quests/$questId/game',
    path: '/quests/$questId/game',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentModulesModuleIdQuizRoute =
  StudentModulesModuleIdQuizRouteImport.update({
    id: '/modules/$moduleId/quiz',
    path: '/modules/$moduleId/quiz',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentModulesModuleIdLessonRoute =
  StudentModulesModuleIdLessonRouteImport.update({
    id: '/modules/$moduleId/lesson',
    path: '/modules/$moduleId/lesson',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentModulesModuleIdGameRoute =
  StudentModulesModuleIdGameRouteImport.update({
    id: '/modules/$moduleId/game',
    path: '/modules/$moduleId/game',
    getParentRoute: () => StudentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/student/grades': typeof StudentGradesRoute
  '/student/join-class': typeof StudentJoinClassRoute
  '/student/progress': typeof StudentProgressRoute
  '/teacher/analytics': typeof TeacherAnalyticsRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/leaderboard': typeof TeacherLeaderboardRoute
  '/teacher/modules': typeof TeacherModulesRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/classes/$classId': typeof StudentClassesClassIdRoute
  '/student/profile/edit': typeof StudentProfileEditRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRoute
  '/teacher/quests/create': typeof TeacherQuestsCreateRoute
  '/student/modules/$moduleId/game': typeof StudentModulesModuleIdGameRoute
  '/student/modules/$moduleId/lesson': typeof StudentModulesModuleIdLessonRoute
  '/student/modules/$moduleId/quiz': typeof StudentModulesModuleIdQuizRoute
  '/student/quests/$questId/game': typeof StudentQuestsQuestIdGameRoute
  '/student/quests/$questId/lesson': typeof StudentQuestsQuestIdLessonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/join-class': typeof StudentJoinClassRoute
  '/student/progress': typeof StudentProgressRoute
  '/teacher/analytics': typeof TeacherAnalyticsRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/leaderboard': typeof TeacherLeaderboardRoute
  '/teacher/modules': typeof TeacherModulesRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/student/classes/$classId': typeof StudentClassesClassIdRoute
  '/student/profile/edit': typeof StudentProfileEditRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRoute
  '/teacher/quests/create': typeof TeacherQuestsCreateRoute
  '/student/modules/$moduleId/game': typeof StudentModulesModuleIdGameRoute
  '/student/modules/$moduleId/lesson': typeof StudentModulesModuleIdLessonRoute
  '/student/modules/$moduleId/quiz': typeof StudentModulesModuleIdQuizRoute
  '/student/quests/$questId/game': typeof StudentQuestsQuestIdGameRoute
  '/student/quests/$questId/lesson': typeof StudentQuestsQuestIdLessonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/student/grades': typeof StudentGradesRoute
  '/student/join-class': typeof StudentJoinClassRoute
  '/student/progress': typeof StudentProgressRoute
  '/teacher/analytics': typeof TeacherAnalyticsRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/leaderboard': typeof TeacherLeaderboardRoute
  '/teacher/modules': typeof TeacherModulesRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/classes/$classId': typeof StudentClassesClassIdRoute
  '/student/profile/edit': typeof StudentProfileEditRoute
  '/teacher/classes_/$classId': typeof TeacherClassesClassIdRoute
  '/teacher/quests/create': typeof TeacherQuestsCreateRoute
  '/student/modules/$moduleId/game': typeof StudentModulesModuleIdGameRoute
  '/student/modules/$moduleId/lesson': typeof StudentModulesModuleIdLessonRoute
  '/student/modules/$moduleId/quiz': typeof StudentModulesModuleIdQuizRoute
  '/student/quests/$questId/game': typeof StudentQuestsQuestIdGameRoute
  '/student/quests/$questId/lesson': typeof StudentQuestsQuestIdLessonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/student'
    | '/teacher'
    | '/student/grades'
    | '/student/join-class'
    | '/student/progress'
    | '/teacher/analytics'
    | '/teacher/classes'
    | '/teacher/dashboard'
    | '/teacher/leaderboard'
    | '/teacher/modules'
    | '/teacher/profile'
    | '/teacher/settings'
    | '/student/'
    | '/teacher/'
    | '/student/classes/$classId'
    | '/student/profile/edit'
    | '/teacher/classes/$classId'
    | '/teacher/quests/create'
    | '/student/modules/$moduleId/game'
    | '/student/modules/$moduleId/lesson'
    | '/student/modules/$moduleId/quiz'
    | '/student/quests/$questId/game'
    | '/student/quests/$questId/lesson'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/student/grades'
    | '/student/join-class'
    | '/student/progress'
    | '/teacher/analytics'
    | '/teacher/classes'
    | '/teacher/dashboard'
    | '/teacher/leaderboard'
    | '/teacher/modules'
    | '/teacher/profile'
    | '/teacher/settings'
    | '/student'
    | '/teacher'
    | '/student/classes/$classId'
    | '/student/profile/edit'
    | '/teacher/classes/$classId'
    | '/teacher/quests/create'
    | '/student/modules/$moduleId/game'
    | '/student/modules/$moduleId/lesson'
    | '/student/modules/$moduleId/quiz'
    | '/student/quests/$questId/game'
    | '/student/quests/$questId/lesson'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/student'
    | '/teacher'
    | '/student/grades'
    | '/student/join-class'
    | '/student/progress'
    | '/teacher/analytics'
    | '/teacher/classes'
    | '/teacher/dashboard'
    | '/teacher/leaderboard'
    | '/teacher/modules'
    | '/teacher/profile'
    | '/teacher/settings'
    | '/student/'
    | '/teacher/'
    | '/student/classes/$classId'
    | '/student/profile/edit'
    | '/teacher/classes_/$classId'
    | '/teacher/quests/create'
    | '/student/modules/$moduleId/game'
    | '/student/modules/$moduleId/lesson'
    | '/student/modules/$moduleId/quiz'
    | '/student/quests/$questId/game'
    | '/student/quests/$questId/lesson'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/settings': {
      id: '/teacher/settings'
      path: '/settings'
      fullPath: '/teacher/settings'
      preLoaderRoute: typeof TeacherSettingsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/profile': {
      id: '/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof TeacherProfileRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/modules': {
      id: '/teacher/modules'
      path: '/modules'
      fullPath: '/teacher/modules'
      preLoaderRoute: typeof TeacherModulesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/leaderboard': {
      id: '/teacher/leaderboard'
      path: '/leaderboard'
      fullPath: '/teacher/leaderboard'
      preLoaderRoute: typeof TeacherLeaderboardRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes': {
      id: '/teacher/classes'
      path: '/classes'
      fullPath: '/teacher/classes'
      preLoaderRoute: typeof TeacherClassesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/analytics': {
      id: '/teacher/analytics'
      path: '/analytics'
      fullPath: '/teacher/analytics'
      preLoaderRoute: typeof TeacherAnalyticsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/join-class': {
      id: '/student/join-class'
      path: '/join-class'
      fullPath: '/student/join-class'
      preLoaderRoute: typeof StudentJoinClassRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/grades': {
      id: '/student/grades'
      path: '/grades'
      fullPath: '/student/grades'
      preLoaderRoute: typeof StudentGradesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/quests/create': {
      id: '/teacher/quests/create'
      path: '/quests/create'
      fullPath: '/teacher/quests/create'
      preLoaderRoute: typeof TeacherQuestsCreateRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes_/$classId': {
      id: '/teacher/classes_/$classId'
      path: '/classes/$classId'
      fullPath: '/teacher/classes/$classId'
      preLoaderRoute: typeof TeacherClassesClassIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/profile/edit': {
      id: '/student/profile/edit'
      path: '/profile/edit'
      fullPath: '/student/profile/edit'
      preLoaderRoute: typeof StudentProfileEditRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/classes/$classId': {
      id: '/student/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/student/classes/$classId'
      preLoaderRoute: typeof StudentClassesClassIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/quests/$questId/lesson': {
      id: '/student/quests/$questId/lesson'
      path: '/quests/$questId/lesson'
      fullPath: '/student/quests/$questId/lesson'
      preLoaderRoute: typeof StudentQuestsQuestIdLessonRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/quests/$questId/game': {
      id: '/student/quests/$questId/game'
      path: '/quests/$questId/game'
      fullPath: '/student/quests/$questId/game'
      preLoaderRoute: typeof StudentQuestsQuestIdGameRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/modules/$moduleId/quiz': {
      id: '/student/modules/$moduleId/quiz'
      path: '/modules/$moduleId/quiz'
      fullPath: '/student/modules/$moduleId/quiz'
      preLoaderRoute: typeof StudentModulesModuleIdQuizRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/modules/$moduleId/lesson': {
      id: '/student/modules/$moduleId/lesson'
      path: '/modules/$moduleId/lesson'
      fullPath: '/student/modules/$moduleId/lesson'
      preLoaderRoute: typeof StudentModulesModuleIdLessonRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/modules/$moduleId/game': {
      id: '/student/modules/$moduleId/game'
      path: '/modules/$moduleId/game'
      fullPath: '/student/modules/$moduleId/game'
      preLoaderRoute: typeof StudentModulesModuleIdGameRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface StudentRouteChildren {
  StudentGradesRoute: typeof StudentGradesRoute
  StudentJoinClassRoute: typeof StudentJoinClassRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentClassesClassIdRoute: typeof StudentClassesClassIdRoute
  StudentProfileEditRoute: typeof StudentProfileEditRoute
  StudentModulesModuleIdGameRoute: typeof StudentModulesModuleIdGameRoute
  StudentModulesModuleIdLessonRoute: typeof StudentModulesModuleIdLessonRoute
  StudentModulesModuleIdQuizRoute: typeof StudentModulesModuleIdQuizRoute
  StudentQuestsQuestIdGameRoute: typeof StudentQuestsQuestIdGameRoute
  StudentQuestsQuestIdLessonRoute: typeof StudentQuestsQuestIdLessonRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentGradesRoute: StudentGradesRoute,
  StudentJoinClassRoute: StudentJoinClassRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentClassesClassIdRoute: StudentClassesClassIdRoute,
  StudentProfileEditRoute: StudentProfileEditRoute,
  StudentModulesModuleIdGameRoute: StudentModulesModuleIdGameRoute,
  StudentModulesModuleIdLessonRoute: StudentModulesModuleIdLessonRoute,
  StudentModulesModuleIdQuizRoute: StudentModulesModuleIdQuizRoute,
  StudentQuestsQuestIdGameRoute: StudentQuestsQuestIdGameRoute,
  StudentQuestsQuestIdLessonRoute: StudentQuestsQuestIdLessonRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAnalyticsRoute: typeof TeacherAnalyticsRoute
  TeacherClassesRoute: typeof TeacherClassesRoute
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  TeacherLeaderboardRoute: typeof TeacherLeaderboardRoute
  TeacherModulesRoute: typeof TeacherModulesRoute
  TeacherProfileRoute: typeof TeacherProfileRoute
  TeacherSettingsRoute: typeof TeacherSettingsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherClassesClassIdRoute: typeof TeacherClassesClassIdRoute
  TeacherQuestsCreateRoute: typeof TeacherQuestsCreateRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAnalyticsRoute: TeacherAnalyticsRoute,
  TeacherClassesRoute: TeacherClassesRoute,
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherLeaderboardRoute: TeacherLeaderboardRoute,
  TeacherModulesRoute: TeacherModulesRoute,
  TeacherProfileRoute: TeacherProfileRoute,
  TeacherSettingsRoute: TeacherSettingsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherClassesClassIdRoute: TeacherClassesClassIdRoute,
  TeacherQuestsCreateRoute: TeacherQuestsCreateRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
